name: CICD

on: push

jobs:
  code:
    runs-on: linux-latest
    steps:
      - name: Code Checkout
        run: echo "Code checkout done"
  build:
    needs: code
    runs-on: linux-latest
    steps:
      - name: Code Build
        run: echo "Code build"
  deploy:
    needs: build
    runs-on: linux-latest
    steps:
      - name: Code deploy
        run: echo "Code Deploy"
  
